### ISSUE TITLE
feat: Should we use Vite Plugin SSR and Tailwind ?

### ISSUE THREAD

**Issue by toey-sup** [nattaaek/fill-you-in-the-blank#13]
### Describe the feature you'd like to request

Hi, just thought it might be beneficial in the future if we use [vite plugin ssr](https://vite-plugin-ssr.com/) to manage routing, SSR, SSG, (or Next.js) and [tailwind](https://tailwindcss.com/) to manage style.

This suggestion is based solely on my opinion, let me know what you think!

(if you wouldn't mind and want to continue chatting, we can talk in the discussion section of this repo)

### Describe the solution you'd like to see

- use tailwind and vite plugin ssr

### 👨‍👧‍👦 Contributing

- [X] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by nattaaek** [comment]
I'm not sure what the benefit of using this plugin is. right now we using react-router-dom in order to do routing stuff. and MUI as the main styling. I knew that tailwind is more lightweight but for me my concern it might end up with something like this.

`<div
  class="w-16 h-16 rounded text-white bg-black py-1 px-2 m-1 text-sm md:w-32 md:h-32 md:rounded-md md:text-base lg:w-48 lg:h-48 lg:rounded-lg lg:text-lg"
>
  Yikes.
</div>`

for me, it is quite harder than the styled component. in term of readability

**Comment by toey-sup** [comment]
I think the main benefit of [vite plugin ssr](https://vite-plugin-ssr.com/) is Filesystem Routing and it help with SSR and SSG (which I think can become handy in the future)

I suggest tailwind because I see that in code you use inline style, which I think in terms of readability tailwind win. but yeah compare to the styled component that is the matter of preference, do you want your styling to be separated or not.

but this is just a suggestion, thank for your reply !

**Comment by toey-sup** [comment]
I use MUI with tailwind before, MUI for components and tailwind for styling

**Comment by nattaaek** [comment]
actually, I'm okay to use tailwind as a styling too. I also think that `sx` is not equal to inline style like `style={{}}`

one of the benefits of this is about `sx` can access MUI theme. so when we have design system it will be very easy in term of accessing the theme value.

https://stackoverflow.com/questions/71014390/what-is-the-purpose-of-sx-prop-in-material-ui

**Comment by nattaaek** [comment]
about the vite plugin. don't we do Client-side rendering? because I didn't use NextJS.

**Comment by nattaaek** [comment]
I'm kind of a bit out of date in front-end technology so I may ask a lot of stupid questions. mainly I use React on a daily work basis and we still use Webpack, not Vite.
