### ISSUE TITLE
Prettier Integration is missing

### ISSUE THREAD

**Issue by nattaaek** [nattaaek/fill-you-in-the-blank#2]
This application still doesn't have Preitter integrate feel free to integrate it. I believe just using build-in standard style is enough

**Comment by glukor** [comment]
Hi @nattaaek , I might have missed something but to run the application, I used `pnpm dev` instead of `pnpm start`. There is no `start` in the `package.json`. You might want to update either the script name or the documentation.

**Comment by nattaaek** [comment]
@glukor Thank you for taking care of this and raising concern about README.md 

https://github.com/nattaaek/fill-you-in-the-blank/pull/6
