### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by nattaaek** [nattaaek/fill-you-in-the-blank#4]
Right now it using the Vite icon please help change it to a favicon inside this drive below 

https://drive.google.com/file/d/1SFQu8CU_wJay4OhjXJIeGYdbBg5-xJkL/view?usp=sharing

**Comment by y4sssh** [comment]
I want to work on this issue

**Comment by nattaaek** [comment]
@Yashdon999  ok

**Comment by y4sssh** [comment]
Hi Bro "pnpm install " command not working

**Comment by nattaaek** [comment]
@Yashdon999 sorry man it should be yarn & yarn dev

**Comment by nattaaek** [comment]
refer to this issue https://github.com/nattaaek/fill-you-in-the-blank/issues/7

**Comment by Yashdon999** [comment]
![Screenshot_2023-03-13_18_04_50](https://user-images.githubusercontent.com/104668751/224703643-59169aca-c82e-46b0-a1a9-a376cf6ec9f6.png)
